---
abstract: 'Passphrases and Passwords as objects for Dancer'
author:
  - 'Henk van Oers <hvo.pm@xs4all.nl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Passphrase
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 1.3118
  Data::Entropy: 0.007
  Digest::Bcrypt: 0
  Digest::SHA: 5.74
  Test::More: 0
resources:
  bugtracker: https://github.com/hvoers/Dancer-Plugin-Passphrase/issues
  homepage: https://github.com/hvoers/Dancer-Plugin-Passphrase/
  repository: https://github.com/hvoers/Dancer-Plugin-Passphrase
version: v2.0.3
