---
abstract: 'Passphrases and Passwords as objects for Dancer'
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires:
  Dancer: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Passphrase
requires:
  Dancer::Plugin: 0
  Data::Entropy::Algorithms: 0.005
  Digest::Bcrypt: 0
  Digest::SHA: 5.008001
  perl: 5.010001
resources:
  bugtracker: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase/issues
  homepage: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase
  repository: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase.git
version: 2.0.0
