---
abstract: 'Passphrases and Passwords as objects for Dancer'
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires:
  Dancer: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Passphrase
requires:
  Dancer::Plugin: '0'
  Data::Entropy::Algorithms: '0.003'
  Digest: '1.16'
  Digest::Bcrypt: '0'
  Digest::SHA: '5.74'
  MIME::Base64: '3.08'
  Scalar::Util: '1.20'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase/issues
  homepage: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase
  repository: https://github.com/LoonyPandora/Dancer-Plugin-Passphrase.git
version: 2.0.1
